name: "ğŸ“ Config Upload"
description: config íŒŒì¼ ì—…ë¡œë“œ
labels: ["config"]
body:
  - type: textarea
    attributes:
      label: ğŸ“„ config ì„¤ëª…
      description: "ì—…ë¡œë“œí•˜ë ¤ëŠ” config íŒŒì¼ì— ëŒ€í•œ ì„¤ëª…ì„ ì‘ì„±í•´ ì£¼ì„¸ìš”."
      placeholder: "ê°„ëµíˆ ì ì–´ì£¼ì…”ë„ ë©ë‹ˆë‹¤"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ“ ê¸°íƒ€ (íŠ¹ì´ ì‚¬í•­)
      description: ê¸°íƒ€ ë„ì›€ì´ ë  ë§Œí•œ ì •ë³´ ë° íŠ¹ì´ ì‚¬í•­ì„ ì‘ì„±í•´ ì£¼ì„¸ìš”.
